version: '3'
services:
  postgres:
    image: "postgres"
  
  redis:
    image: "redis"

  backend:
    container_name: 'backend'
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  frontend:
    container_name: 'frontend'
    build: ./makestorytogether
    ports:
      - "3000:3000"
    