version: '3'
services:
  postgres:
    image: "postgres"
  
  redis:
    image: "redis"

  backend:
    container_name: 'backend'
    build: ./backend
      # context: ./backend
      # dockerfile: Dockerfile
      # args:
      #   location: China
    command: bash ./docker-entrypoint.sh
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  frontend:
    container_name: 'frontend'
    build: ./makestorytogether
      # context: ./makestorytogether
      # dockerfile: Dockerfile
      # args:
      #   location: China
    command: yarn start
    volumes:
      - ./makestorytogether:/makestorytogether
    ports:
      - "3000:3000"
    